Dockerfile
docker-compose.local.yml
docker-compose.yml
src/modules/auth/auth.controller.ts
startup.dev.sh
wait-for-it.sh

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-2][QUIZ-23] fix: update docker for migration database

---

src/modules/file/file.controller.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-18][QUIZ-87] config: config swagger for uploading multipart form

---

src/core/decorators/upload-file.decorator.ts
src/modules/file/dto/file-info.res.dto.ts
src/modules/file/file.controller.ts
src/modules/file/file.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-18][QUIZ-87] update: add original_filename to info response

---

package-lock.json
package.json
src/app.module.ts
src/core/constants/error-code.constant.ts
src/database/migrations/1728379380000-create-quizzfly-table.ts
src/main.ts
src/modules/quizzfly/dto/request/setting-quizzfly.request.ts
src/modules/quizzfly/dto/response/info-detail-quizzfly.response.ts
src/modules/quizzfly/dto/response/info-quizzfly.response.ts
src/modules/quizzfly/entity/enums/quizzfly-status.enum.ts
src/modules/quizzfly/entity/quizzfly.entity.ts
src/modules/quizzfly/quizzfly.controller.ts
src/modules/quizzfly/quizzfly.module.ts
src/modules/quizzfly/quizzfly.service.ts
src/modules/quizzfly/repository/quizzfly.repository.ts
src/modules/user/entities/user.entity.ts
src/modules/user/user.service.ts
src/shared/modules-set.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-59] [QUIZ-58] feature: api create draft quizzfly

---

src/modules/auth/auth.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-35] hotfix: fix hash password when reset password

---

src/modules/auth/auth.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-35] hotfix: fix reset password error

---

src/app.module.ts
src/core/constants/error-code.constant.ts
src/database/migrations/1728996420000-create-slide-table.ts
src/modules/quizzfly/dto/request/setting-quizzfly.req.ts
src/modules/quizzfly/dto/response/info-detail-quizzfly.res.ts
src/modules/quizzfly/entity/quizzfly.entity.ts
src/modules/quizzfly/quizzfly.controller.ts
src/modules/quizzfly/quizzfly.module.ts
src/modules/quizzfly/quizzfly.service.ts
src/modules/quizzfly/repository/quizzfly.repository.ts
src/modules/slide/dto/request/update-slide.req.ts
src/modules/slide/dto/response/info-slide.res.ts
src/modules/slide/entity/slide.entity.ts
src/modules/slide/repository/slide.repository.ts
src/modules/slide/slide.controller.ts
src/modules/slide/slide.module.ts
src/modules/slide/slide.service.ts
src/modules/user/dto/request/change-password.req.ts
src/modules/user/user.controller.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-48][QUIZ-97] feat: api create, update, duplicate, delete slide

---

docker-compose.yml
package-lock.json
package.json
src/common/common.function.ts
src/config/config.type.ts
src/core/constants/cache.constant.ts
src/core/constants/error-code.constant.ts
src/libs/redis/config/redis-config.type.ts
src/libs/redis/config/redis.config.ts
src/libs/redis/utils/cache-ttl.utils.ts
src/libs/redis/utils/create-cache-key.utils.ts
src/mail/mail.service.ts
src/mail/templates/request-delete.hbs
src/modules/user/user.controller.ts
src/modules/user/user.service.ts
src/shared/modules-set.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-2][QUIZ-112] feat: api request delete, api verify delete account, config redis

---

src/app.module.ts
src/common/common.function.ts
src/config/config.type.ts
src/core/constants/error-code.constant.ts
src/database/migrations/1729668120000-create-room-table.ts
src/libs/redis/config/redis.config.ts
src/libs/redis/utils/create-cache-key.utils.ts
src/modules/quizzfly/entity/quizzfly.entity.ts
src/modules/room/dto/request/create-room.req.ts
src/modules/room/dto/request/setting-room.req.ts
src/modules/room/dto/response/info-room.res.ts
src/modules/room/entity/enums/room-status.enum.ts
src/modules/room/entity/room.entity.ts
src/modules/room/repository/room.repository.ts
src/modules/room/room.controller.ts
src/modules/room/room.module.ts
src/modules/room/room.service.ts
src/modules/slide/slide.service.ts
src/modules/user/entities/user.entity.ts
src/modules/user/user.service.ts
src/shared/modules-set.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-95][QUIZ-114] feat: api create room, get detail room, setting room

---

src/modules/answer/answer.controller.ts
src/modules/answer/answer.service.ts
src/modules/auth/auth.controller.ts
src/modules/auth/auth.service.ts
src/modules/quizzfly/quizzfly.service.ts
src/modules/quizzfly/repository/quizzfly.repository.ts
src/modules/session/session.service.ts
src/modules/user/user.module.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

feat: api revoke token, add list answer api get list question

---

docker-compose.yml

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-111] fix: send mail for gmail of user

---

src/app.module.ts
src/core/constants/app.constant.ts
src/libs/socket/model/user-in-socket.ts
src/libs/socket/payload/request/create-room.req.ts
src/libs/socket/payload/request/join-room.req.ts
src/libs/socket/socket.gateway.ts
src/modules/answer/answer.service.ts
src/modules/quiz/dto/response/quiz.res.dto.ts
src/modules/quiz/entities/quiz.entity.ts
src/modules/quiz/quiz.module.ts
src/modules/quiz/quiz.service.ts

…cate quiz
- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

fix: update default value for quiz entity and copy answers when duplicate quiz

---

src/core/constants/app.constant.ts
src/modules/auth/auth.controller.ts
src/modules/auth/auth.module.ts
src/modules/auth/auth.service.ts
src/modules/auth/dto/request/login-with-google.req.dto.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-2][QUIZ-37] feat: login with google

---

src/core/decorators/ws-current-user.decorator.ts
src/core/filters/ws-exception.filter.ts
src/libs/socket/enums/role-in-room.enum.ts
src/libs/socket/model/player.model.ts
src/libs/socket/model/room-socket.ts
src/libs/socket/model/room.model.ts
src/libs/socket/model/user-in-socket.ts
src/libs/socket/payload/request/start-quiz.req.dto.ts
src/libs/socket/payload/response/quiz-started.res.dto.ts
src/libs/socket/socket.gateway.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-128] feat: lock - unlock room and start quiz by host

---

src/core/constants/app.constant.ts
src/core/core.module.ts
src/core/events/event.interface.ts
src/core/events/event.service.ts
src/libs/socket/model/player.model.ts
src/libs/socket/model/room-socket.ts
src/libs/socket/model/room.model.ts
src/libs/socket/model/user.model.ts
src/libs/socket/payload/request/join-room.req.ts
src/libs/socket/payload/request/start-quiz.req.dto.ts
src/libs/socket/payload/response/quiz-started.res.dto.ts
src/libs/socket/socket.gateway.ts
src/modules/auth/auth.controller.ts
src/modules/auth/auth.module.ts
src/modules/auth/auth.service.ts
src/modules/auth/dto/request/login-with-google.req.dto.ts
src/modules/quizzfly/events/quizzfly.event.ts
src/modules/quizzfly/quizzfly.controller.ts
src/modules/quizzfly/quizzfly.service.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-128] feat: handle event start quiz and send next question

---

src/core/helpers/index.ts
src/core/interceptors/ws-response.interceptor.ts
src/libs/socket/model/room.model.ts
src/libs/socket/model/user.model.ts
src/libs/socket/socket.gateway.ts
src/libs/socket/utils/calculate-score.util.ts

…ult answer - summary answer
- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-130][QUIZ-135] feat: handle event answer question - finish question - result answer - summary answer

---

src/libs/socket/model/user.model.ts
src/libs/socket/payload/request/kick-player.req.ts
src/libs/socket/socket.gateway.ts
src/modules/quizzfly/quizzfly.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-136] feat: kick member in room

---

src/core/filters/ws-exception.filter.ts
src/libs/socket/payload/request/kick-player.req.ts
src/libs/socket/socket.gateway.ts
src/modules/quizzfly/quizzfly.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

chore: handle exception for socket gateway

---

docker-compose.yml
src/core/pipes/ws-validation.pipe.ts
src/libs/socket/helpers/update-leader-board.helper.ts
src/libs/socket/model/user.model.ts
src/libs/socket/payload/request/answer-question.req.dto.ts
src/libs/socket/payload/request/create-room.req.dto.ts
src/libs/socket/payload/request/create-room.req.ts
src/libs/socket/payload/request/finish-question.req.dto.ts
src/libs/socket/payload/request/join-room.req.dto.ts
src/libs/socket/payload/request/join-room.req.ts
src/libs/socket/payload/request/update-leader-board.req.dto.ts
src/libs/socket/payload/room-pin.dto.ts
src/libs/socket/socket.gateway.ts
src/libs/socket/utils/calculate-score.util.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-138] feat: handle event update leaderboard

---

src/app.module.ts
src/database/migrations/1731570060000-create-table-member-in-group-and-table-group.ts
src/modules/group/dto/request/create-group.req.dto.ts
src/modules/group/dto/response/info-detail-group.res.dto.ts
src/modules/group/dto/response/info-group.res.dto.ts
src/modules/group/entity/group.entity.ts
src/modules/group/entity/member-in-group.entity.ts
src/modules/group/enums/role-in-group.enum.ts
src/modules/group/group.controller.ts
src/modules/group/group.module.ts
src/modules/group/group.service.ts
src/modules/group/member-in-group.service.ts
src/modules/group/repository/group.repository.ts
src/modules/group/repository/member-in-group.repository.ts
src/modules/user/entities/user.entity.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

feat: api create group, get my group

---

src/libs/socket/model/room.model.ts
src/libs/socket/socket.gateway.ts
src/libs/socket/utils/calculate-score.util.ts
src/modules/quizzfly/repository/quizzfly.repository.ts

…nswers
- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

 [QUIZ-141] fix: fix answers real time play game and update order of answers

---

src/app.module.ts
src/database/migrations/1731570060000-create-table-member-in-group-and-table-group.ts
src/libs/socket/socket.gateway.ts
src/modules/group/dto/request/create-group.req.dto.ts
src/modules/group/dto/response/info-detail-group.res.dto.ts
src/modules/group/dto/response/info-group.res.dto.ts
src/modules/group/entity/group.entity.ts
src/modules/group/entity/member-in-group.entity.ts
src/modules/group/group.controller.ts
src/modules/group/group.module.ts
src/modules/group/group.service.ts
src/modules/group/member-in-group.service.ts
src/modules/group/repository/group.repository.ts
src/modules/group/repository/member-in-group.repository.ts
src/modules/user/entities/user.entity.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-139] feat: handle disconected room for host - player

---

src/libs/socket/socket.gateway.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-139] hotfix: handle exception when run out of question

---

docker-compose.yml
src/core/constants/error-code/error-code-detail.constant.ts
src/core/constants/error-code/error-code.constant.ts
src/core/constants/error-code/quiz-error-code.constant.ts
src/core/events/event.service.ts
src/generated/i18n.generated.ts
src/i18n/en/quiz.json
src/libs/socket/socket.gateway.ts
src/modules/answer/answer.service.ts
src/modules/answer/events/index.ts
src/modules/quiz/events/index.ts
src/modules/quiz/quiz.service.ts
src/modules/quizzfly/quizzfly.service.ts
src/modules/slide/events/index.ts
src/modules/slide/slide.service.ts

… answer is correct
- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-155] fix: reponse array answer when duplicate quiz and only one answer is correct

---

src/core/filters/global-exception.filter.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

hotfix: handle invalid key i18n

---

src/database/migrations/1732029089237-update-answer-table-add-column-index.ts
src/modules/answer/answer.service.ts
src/modules/answer/dto/request/create-answer.req.dto.ts
src/modules/answer/dto/response/answer.res.dto.ts
src/modules/answer/entities/answer.entity.ts
src/modules/answer/events/index.ts
src/modules/quiz/dto/request/create-multiple-quiz-generated.req.dto.ts
src/modules/quiz/dto/request/create-quiz-generated.req.dto.ts
src/modules/quiz/dto/response/quiz.res.dto.ts
src/modules/quiz/entities/quiz.entity.ts
src/modules/quiz/quiz.controller.ts
src/modules/quiz/quiz.service.ts
src/modules/quizzfly/repository/quizzfly.repository.ts

…atch quiz
- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-164] feat: add field index for answer entity - api for create batch quiz

---

src/core/constants/app.constant.ts
src/modules/answer/entities/answer.entity.ts
src/modules/quiz/entities/quiz.entity.ts
src/modules/quiz/quiz.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-164] hotfix: update response data when create batch quiz

---

src/common/dto/base.res.dto.ts
src/modules/quiz/dto/request/update-quiz.req.dto.ts
src/modules/quiz/events/index.ts
src/modules/quiz/quiz.service.ts
src/modules/quizzfly/dto/request/change-theme-quizzfly.req.ts
src/modules/quizzfly/dto/response/info-detail-quizzfly.res.ts
src/modules/quizzfly/quizzfly.service.ts
src/modules/slide/events/index.ts
src/modules/slide/slide.service.ts

… quizzfly
- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-142] feat: api settting background for all quiz and answer in a quizzfly

---

src/core/helpers/index.ts
src/libs/socket/model/room.model.ts
src/libs/socket/payload/request/setting-room.req.dto.ts
src/libs/socket/socket.gateway.ts
src/modules/room/dto/response/info-room.res.ts
src/modules/room/events/index.ts
src/modules/room/events/setting-room.event.ts
src/modules/room/room.controller.ts
src/modules/room/room.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-153] feat: handle event setting room when play quiz

---

src/libs/socket/payload/request/setting-room.req.dto.ts
src/libs/socket/socket.gateway.ts
src/modules/quiz/dto/request/create-multiple-quiz-generated.req.dto.ts
src/modules/quiz/dto/request/create-quiz-generated.req.dto.ts

…pty array
- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-153] hotfix: update body for event setting room and validate empty array for api create batch quiz

---

src/modules/group/repository/post.repository.ts
src/modules/user/user.controller.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-160] feat: api get info detail user by id, update response api get list post

---

src/database/migrations/1732545240000-create-table-react-post.ts
src/database/migrations/1732632300000-create-table-comment-post.ts
src/modules/group/controller/post.controller.ts
src/modules/group/dto/request/comment-post.req.dto.ts
src/modules/group/dto/response/info-comment-post.res.dto.ts
src/modules/group/dto/response/info-post.res.dto.ts
src/modules/group/entity/comment-post.entity.ts
src/modules/group/entity/post.entity.ts
src/modules/group/entity/react-post.entity.ts
src/modules/group/group.module.ts
src/modules/group/repository/comment-post.repository.ts
src/modules/group/repository/post.repository.ts
src/modules/group/repository/react-post.repository.ts
src/modules/group/service/post.service.ts
src/modules/user/entities/user.entity.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-160] feat: api react post

---

src/modules/group/dto/response/info-post.res.dto.ts
src/modules/group/mapper/post.mapper.ts
src/modules/group/repository/post.repository.ts
src/modules/group/service/post.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-160] update: format info response list post

---

src/common/dto/base.res.dto.ts
src/core/helpers/index.ts
src/modules/file/dto/file.res.dto.ts
src/modules/group/dto/response/info-post.res.dto.ts
src/modules/group/repository/post.repository.ts
src/modules/group/service/post.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-160] fix: update response data for api get list post

---

src/modules/group/group.module.ts
src/modules/group/service/post.service.ts
src/modules/group/socket/enums/group-event.enum.ts
src/modules/group/socket/group-socket.gateway.ts
src/modules/group/socket/payload/request/register-group.req.dto.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-144][QUIZ-152] feat: realtime group

---

src/modules/group/dto/response/info-comment-post.res.dto.ts
src/modules/group/repository/comment-post.repository.ts
src/modules/group/socket/group-socket.gateway.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-159] update: add info replies comment in api get comments

---

src/modules/group/dto/response/info-post.res.dto.ts
src/modules/group/socket/group-socket.gateway.ts
src/modules/quizzfly/dto/request/setting-quizzfly.req.ts
src/modules/quizzfly/dto/response/quizzfly-detail.res.ts
src/modules/quizzfly/dto/response/quizzfly.res.ts
src/modules/quizzfly/quizzfly.controller.ts
src/modules/quizzfly/quizzfly.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-134] feat: update body request for setting quizzfly

---

src/modules/group/dto/response/info-comment-post.res.dto.ts
src/modules/group/repository/comment-post.repository.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

[QUIZ-159] update: remove info replies comment in api get comments

---

src/modules/room/model/participant.model.ts
src/modules/room/payload/response/question.dto.ts
src/modules/room/payload/response/quiz-started.dto.ts
src/modules/room/room.gateway.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

hotfix: update type timestamp and list answer for event room socket

---

src/app.module.ts
src/core/constants/error-code/error-code.constant.ts
src/database/migrations/1733914320000-create-notification-table.ts
src/modules/group/dto/response/info-comment-post.res.dto.ts
src/modules/group/group.module.ts
src/modules/group/repository/comment-post.repository.ts
src/modules/group/service/comment.service.ts
src/modules/group/service/member-in-group.service.ts
src/modules/group/service/post.service.ts
src/modules/notification/controller/notification.controller.ts
src/modules/notification/dto/request/create-notification.dto.ts
src/modules/notification/dto/response/notification.res.dto.ts
src/modules/notification/entity/notification.entity.ts
src/modules/notification/enums/notification-type.enum.ts
src/modules/notification/notification.module.ts
src/modules/notification/repository/notification.repository.ts
src/modules/notification/service /notification.service.ts
src/modules/notification/service /push-notification.service.ts
src/modules/notification/socket/enums/notification-event.enum.ts
src/modules/notification/socket/notification-socket.gateway.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

feat: notification apis

---

src/modules/notification/dto/response/notification.res.dto.ts
src/modules/notification/service/notification.service.ts
src/modules/notification/service/push-notification.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

update: update info response api get list notification

---

src/database/migrations/1734176700000-add-description-in-notification-table.ts
src/modules/group/service/comment.service.ts
src/modules/notification/dto/request/create-notification.dto.ts
src/modules/notification/dto/response/notification.res.dto.ts
src/modules/notification/entity/notification.entity.ts
src/modules/notification/service/notification.service.ts
src/modules/notification/service/push-notification.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

update: add description column to notification table

---

src/common/dto/offset-pagination/page-options.dto.ts
src/modules/user/controller/admin-user.controller.ts
src/modules/user/controller/user.controller.ts
src/modules/user/dto/response/user.res.dto.ts
src/modules/user/repositories/user.repository.ts
src/modules/user/user.module.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

feat: api admin user

---

src/modules/quizzfly/dto/request/admin-query-quizzfly.req.dto.ts
src/modules/user/dto/request/admin-query-user.req.dto.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

update: not require query param is_deleted

---

src/modules/group/controller/admin-group.controller.ts
src/modules/group/group.module.ts
src/modules/group/repository/group.repository.ts
src/modules/group/service/comment.service.ts
src/modules/group/service/group.service.ts
src/modules/group/service/post.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

feat: api group admin

---

src/modules/auth/auth.service.ts
src/modules/quizzfly/dto/request/admin-query-quizzfly.req.dto.ts
src/modules/quizzfly/dto/request/query-quizzfly.req.dto.ts
src/modules/quizzfly/dto/response/quizzfly-detail.res.ts
src/modules/quizzfly/quizzfly.service.ts
src/modules/quizzfly/repository/quizzfly.repository.ts
src/modules/user/dto/request/admin-query-user.req.dto.ts
src/modules/user/dto/response/user-info.res.dto.ts
src/modules/user/dto/response/user.res.dto.ts
src/modules/user/entities/user.entity.ts
src/modules/user/repositories/user.repository.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

fix: update api paginate

---

src/modules/quizzfly/dto/request/admin-query-quizzfly.req.dto.ts
src/modules/quizzfly/quizzfly.service.ts
src/modules/quizzfly/repository/quizzfly.repository.ts
src/modules/user/dto/request/admin-query-user.req.dto.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

fix: update api admin get list user

---

src/modules/role/events/get-role.event.ts
src/modules/role/role.controller.ts
src/modules/role/role.module.ts
src/modules/role/role.service.ts
src/modules/user/repositories/user.repository.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

feat: api get list user by role - api assign role for user

---

src/modules/answer/dto/response/answer.res.dto.ts
src/modules/room/dto/response/question.res.dto.ts
src/modules/room/room.gateway.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

fix: add number of participant choice answer

---

src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

fix: api restore user

---

src/common/common.function.ts
src/database/migrations/1735384140000-create-table-user-plan.ts
src/database/migrations/1735446900000-create-table-usage-resource.ts
src/database/migrations/1735453740000-update-type-paymented_at.ts
src/modules/notification/notification.module.ts
src/modules/notification/service/push-notification.service.ts
src/modules/notification/socket/enums/notification-event.enum.ts
src/modules/notification/socket/notification-socket.gateway.ts
src/modules/subscription/controller/user-plan.controller.ts
src/modules/subscription/dto/request/webhook-payment-update.req.dto.ts
src/modules/subscription/dto/response/user-plan.res.dto.ts
src/modules/subscription/entity/subscription-plan.entity.ts
src/modules/subscription/entity/usage-resource.entity.ts
src/modules/subscription/entity/user-plan.entity.ts
src/modules/subscription/enum/user-plan-status.enum.ts
src/modules/subscription/repository/usage-resource.repository.ts
src/modules/subscription/repository/user-plan.repository.ts
src/modules/subscription/service/resource-limit.service.ts
src/modules/subscription/service/user-plan.service.ts
src/modules/subscription/subscription.module.ts
src/modules/user/entities/user.entity.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

feat: api pay a subscription plan by user

---

src/core/constants/error-code/error-code-detail.constant.ts
src/core/constants/error-code/error-code.constant.ts
src/core/constants/error-code/resource-limit-error-code.constant.ts
src/core/constants/error-code/subscription-error-code.constant.ts
src/generated/i18n.generated.ts
src/i18n/en/resourceLimit.json
src/i18n/en/subscriptionPlan.json
src/modules/subscription/controller/resource-limit.controller.ts
src/modules/subscription/controller/subscription-plan.controller.ts
src/modules/subscription/dto/request/create-resource-limit.req.dto.ts
src/modules/subscription/dto/request/create-subscription-plan.req.dto.ts
src/modules/subscription/dto/request/update-subscription-plan.req.dto.ts
src/modules/subscription/dto/response/subscription-plan.res.dto.ts
src/modules/subscription/service/resource-limit.service.ts
src/modules/subscription/service/subscription-plan.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

fix: update api create subscription plan

---

package-lock.json
package.json
src/common/common.function.ts
src/common/gemini.ai.ts
src/core/constants/app.constant.ts
src/modules/quiz/dto/request/generate-quiz-by-ai.req.dto.ts
src/modules/quiz/dto/request/option-generate-quiz-by-ai.req.dto.ts
src/modules/quiz/quiz.controller.ts
src/modules/quiz/quiz.module.ts
src/modules/quiz/quiz.service.ts
src/modules/subscription/controller/user-plan.controller.ts
src/modules/subscription/dto/response/user-plan.res.dto.ts
src/modules/subscription/repository/user-plan.repository.ts
src/modules/subscription/service/user-plan.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

feat: api generate quiz by AI, fix user plan

---

src/modules/auth/auth.service.ts
src/modules/user/user.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

fix: fix login google

---

src/modules/group/controller/post.controller.ts
src/modules/group/dto/response/info-shared.rest.dto.ts
src/modules/group/group.module.ts
src/modules/group/repository/post.repository.ts
src/modules/group/service/post.service.ts
src/modules/room/dto/request/create-room.req.ts
src/modules/room/room.module.ts
src/modules/room/services/room.service.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

fix: fix bug Dong log

---

src/core/constants/error-code/room-error-code.constant.ts
src/core/filters/global-exception.filter.ts
src/modules/slide/dto/response/info-slide.res.ts

- 🐛 Bug Fix
- 🎉 Release
- 👕 Fix (Lint)
- 👾 Others

hotfix: update response for api create slide
